name: "coretelecoms_dbt"
version: "1.0.0"

# Link this project to the correct dbt profile
profile: "coretelecoms_dbt"

# Folders for project resources
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

# Target directory for compiled SQL
target-path: "target"

# Directories removed on `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations by folder
models:  
  staging:
    +materialized: view
    +schema: staging
  intermediate:
    +materialized: table
    +schema: intermediate
  datawarehouse:
    +materialized: table
    +schema: datawarehouse
