coretelecoms_dbt:
  target: prod

  outputs:

    dev:
      type: bigquery
      method: service-account
      project: "onyx-cosmos-480018-k1"
      dataset: "coretelecoms_capstone_datawarehouse"
      threads: 8
      keyfile: "/opt/airflow/.creds/coretelecoms.json"
      timeout_seconds: 300
      location: "us-central1"
      priority: "interactive"

    prod:
      type: bigquery
      method: service-account
      project: "onyx-cosmos-480018-k1"
      dataset: "coretelecoms_capstone_datawarehouse"
      threads: 16
      keyfile: "/opt/airflow/.creds/coretelecoms.json"
      timeout_seconds: 600
      location: "us-central1"
      priority: "batch"
      retries: 3

    ci:
      type: bigquery
      method: service-account
      project: "onyx-cosmos-480018-k1"
      dataset: "coretelecoms_capstone_datawarehouse"
      threads: 4
      keyfile: "/opt/airflow/.creds/coretelecoms.json"
      location: "us-central1"
